### ISSUE TITLE
Не могли бы объяснить работу Вашего алгоритма

### ISSUE THREAD

**Issue by Soarex16** [vearutop/php-obscene-censor-rus#13]
Занимаюсь его портированием (как выложу на гитхаб - укажу ссылку на Ваш репозиторий) на Java 8, и некоторые части вашего кода просто не понимаю)

Заранее благодарю)

**Comment by vearutop** [comment]
По сути это все большое регулярное выражение с унифицированными символами.

Таблица букв с их альтернативными "написаниями":

``` php
    private static $LT_P = 'пПnPp';
    private static $LT_I = 'иИiI1u';
....
```

Словарь ложно-позитивных строк, при нахождении строки из списка матовая маркировка снимается:

``` php
    public static $exceptions = array(
        'команд',
```

Основная функция поиска

``` php
    public static function filterText(&$text, $charset = 'UTF-8')
```

Если входящая строка не в юникоде, она конвертируется

``` php
        if ($charset !== $utf8) {
            $text = iconv($charset, $utf8, $text);
        }
```

С помощью таблицы альтернативных написаний букв создается регулярное выражение для поиска матершинных корней (корни перечислены с логикой ИЛИ `|`):

``` php
        preg_match_all('/
\b\d*(
    \w*[' . self::$LT_P . '][' . self::$LT_I . self::$LT_E . '][' . self::$LT_Z . '][' . self::$LT_D . ']\w* # пизда
|
    (?:[^' . self::$LT_I . self::$LT_U . '\s]+|' . self::$LT_N . self::$LT_I . ')?(?<!стра)[' . self::$LT_H . '][' . self::$LT_U . '][' . self::$LT_YI . self::$LT_E . self::$LT_YA . self::$LT_YO . self::$LT_I . self::$LT_L . self::$LT_YU . '](?!иг)\w* # хуй; не пускает "подстрахуй", "хулиган"
|
```

В результате получается выражение:

```
/
\b\d*(
    \w*[пПnPp][иИiI1uеЕeE][зЗ3zZ3][дДdD]\w* # пизда
|
    (?:[^иИiI1uуУyYuU\s]+|нНhHиИiI1u)?(?<!стра)[хХxXhH][уУyYuU][йЙyеЕeEяЯёЁиИiI1uлЛlLюЮ](?!иг)\w* # хуй; не пускает "подстрахуй", "хулиган"
|
    \w*[бБ6bB][лЛlL](?:
        [яЯ]+[дДdDтТtT]?
        |
        [иИiI1u]+[дДdDтТtT]+
        |
        [иИiI1u]+[аАaA]+
    )(?!х)\w* # бля, блядь; не пускает "бляха"
|
    (?:
        \w*[йЙyуУyYuUеЕeEаАaAоОoO0ъЪьЬыЫяЯ][еЕeEёЁяЯиИiI1u][бБ6bBпПnPp](?!ы\b|ол)\w* # не пускает "еёбы", "наиболее", "наибольшее"...
        |
        [еЕeEёЁ][бБ6bB]\w*
        |
        [иИiI1u][бБ6bB][аАaA]\w+
        |
        [йЙy][оОoO0][бБ6bBпПnPp]\w*
    ) # ебать
|
    \w*[сСcCsS][цЦcC]?[уУyYuU]+(?:
        [чЧ4]*[кКkK]+
        |
        [чЧ4]+[кКkK]*
    )[аАaAоОoO0]\w* # сука
|
    \w*(?:
        [пПnPp][иИiI1uеЕeE][дДdD][аАaAоОoO0еЕeE]?[рРpPrR](?!о)\w* # не пускает "Педро"
        |
        [пПnPp][еЕeE][дДdD][еЕeEиИiI1u]?[гГgGкКkK]
    ) # пидарас
|
    \w*[зЗ3zZ3][аАaAоОoO0][лЛlL][уУyYuU][пПnPp]\w* # залупа
|
    \w*[мМmM][аАaA][нНhH][дДdD][аАaAоОoO0]\w* # манда
)\b
/xu
```

Регулярное выражение ([PCRE](http://php.net/manual/ru/reference.pcre.pattern.syntax.php)) проверяет каждое слово строки на соответствие хотя бы одному из матершинных корней.

Результат поиска в переменной `$m[1]`.

В случае положительного срабатывания регулярного выражения (матершинный корень найден), происходит сравнение (без учета регистра символов) подозрительного слова со списком ложно-положительных исключений. Слова исключения исключаются из результатов поиска.

Если подозрительное слово не является исключением оно очищается от пунктуационных символов

``` php
                    $m[1][$i] = str_replace(array(' ', ',', ';', '.', '!', '-', '?', "\t", "\n"), '', $m[1][$i]);
```

После этого подготавливается массив звездных масок (строка `***` такой же длины как найденое слово) для каждого из найденых слов.

``` php
            $asterisks = array();
            foreach ($m[1] as $word) {
                if (is_array(self::$log)) {
                    $t = &self::$log[$word];
                    ++$t;
                }
                $asterisks []= str_repeat('*', mb_strlen($word, $utf8));
            }
```

Массив найденных слов заменяется на массив звездированных слов для всей входящей строки

``` php
            $text = str_replace($m[1], $asterisks, $text);
```

Производится обратное преобразование кодировки при необходимости

``` php
            if ($charset !== $utf8) {
                $text = iconv($utf8, $charset, $text);
            }
```

Недостаток текущей реализации - высокая вероятность ложноположительного срабатывания для английских слов. В планах набрать хорошую репрезентативную текстовую базу матов (например из сообщений на [форуме школьников Ноггано](http://gazgolder.com/noggano/forum/) :)) и произвести тонкую настройку регулярного выражения.

**Comment by Soarex16** [comment]
Огромное спасибо!)
